### ISSUE TITLE
progress callback doesn't work

### ISSUE THREAD

**Issue by coryvirok** [lericson/simples3#16]
```
fp = ProgressCallingFile(fp, progress)
...

TypeError: __init__() takes exactly 4 arguments (3 given)
```

**Comment by lericson** [comment]
Correct, it should be fixed. The signature is actually `ProgressCallingFile(fp, size, progress)`. Where did you get this? The documentation?

**Comment by coryvirok** [comment]
Haven't tried it since I filed the issue, but I got the usage from here: https://github.com/lericson/simples3/blob/master/simples3/streaming.py#L64

**Comment by lericson** [comment]
I will look into fixing this when I have the time.

-Ludvig
